const TOOLS = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "World's most used AI chatbot — free tier available",
    description: "ChatGPT by OpenAI lets you write, code, analyze, and brainstorm. The free tier gives access to GPT-4o mini with generous daily limits. Perfect for students, freelancers, and everyday tasks.",
    category: "Chatbot",
    tags: ["writing", "coding", "research"],
    url: "https://chat.openai.com",
    rating: 4.9,
    reviews: 12400,
    badge: "Most Popular",
    free_tier: "Free forever (limited)"
  },
  {
    id: "claude",
    name: "Claude",
    tagline: "Honest, thoughtful AI — great at long documents",
    description: "Claude by Anthropic is known for nuanced and safe responses. Excellent at reading long documents, writing essays, and deep analysis. Free tier available with daily limits.",
    category: "Chatbot",
    tags: ["writing", "analysis", "documents"],
    url: "https://claude.ai",
    rating: 4.8,
    reviews: 8200,
    badge: "Editor's Pick",
    free_tier: "Free forever (limited)"
  },
  {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Google's AI — search-powered and multimodal",
    description: "Gemini combines Google Search with generative AI. Summarize, create, and analyze images. Integrated with Google Docs, Gmail, and Drive.",
    category: "Chatbot",
    tags: ["search", "multimodal", "google"],
    url: "https://gemini.google.com",
    rating: 4.7,
    reviews: 9100,
    badge: "Free",
    free_tier: "Free forever"
  },
  {
    id: "microsoft-copilot",
    name: "Microsoft Copilot",
    tagline: "Free GPT-4 + DALL-E by Microsoft, no account needed",
    description: "Microsoft's free AI powered by GPT-4 and DALL-E 3. Unlimited chat, image generation, and web browsing. No account required to start using it.",
    category: "Chatbot",
    tags: ["chatbot", "images", "free unlimited"],
    url: "https://copilot.microsoft.com",
    rating: 4.6,
    reviews: 7700,
    badge: "Free Unlimited",
    free_tier: "Unlimited free"
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    tagline: "Design anything with AI — no skills needed",
    description: "Canva's AI tools let you generate images, remove backgrounds, and write copy. Free tier includes Magic Write, background remover, and monthly AI image generation credits.",
    category: "Design",
    tags: ["design", "images", "social media"],
    url: "https://canva.com",
    rating: 4.8,
    reviews: 15300,
    badge: "Most Popular",
    free_tier: "Free with limits"
  },
  {
    id: "remove-bg",
    name: "Remove.bg",
    tagline: "Remove image backgrounds instantly — 100% free",
    description: "The fastest AI background remover online. Upload any image and get a clean cutout in under 5 seconds. Free tier gives HD previews with unlimited low-res downloads.",
    category: "Design",
    tags: ["background removal", "images", "editing"],
    url: "https://remove.bg",
    rating: 4.7,
    reviews: 6700,
    badge: "Free",
    free_tier: "Free (low-res)"
  },
  {
    id: "ideogram",
    name: "Ideogram",
    tagline: "AI image generator that actually gets text right",
    description: "Ideogram excels at generating text within images — logos, posters, and typography. Free plan gives 10 slow generations per day. Great for designers and marketers.",
    category: "Image Generation",
    tags: ["images", "design", "logos", "text-in-images"],
    url: "https://ideogram.ai",
    rating: 4.6,
    reviews: 3800,
    badge: "Trending",
    free_tier: "Free (10/day)"
  },
  {
    id: "capcut",
    name: "CapCut",
    tagline: "TikTok's AI video editor — insanely powerful for free",
    description: "CapCut is ByteDance's free video editor packed with AI features — auto captions, background removal, AI avatars, text-to-speech, and viral templates. Used by millions of creators worldwide.",
    category: "Video",
    tags: ["video editing", "captions", "tiktok", "reels"],
    url: "https://capcut.com",
    rating: 4.8,
    reviews: 18900,
    badge: "Most Popular",
    free_tier: "Free forever"
  },
  {
    id: "runway",
    name: "Runway ML",
    tagline: "AI video generation and editing for creators",
    description: "Runway is a powerful AI creative suite. Generate videos from text, remove backgrounds from video, and inpaint objects. Free plan includes 125 generation credits per month.",
    category: "Video",
    tags: ["video", "generation", "editing"],
    url: "https://runwayml.com",
    rating: 4.6,
    reviews: 4200,
    badge: "Trending",
    free_tier: "Free (125 credits/mo)"
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    tagline: "AI voice cloning and text-to-speech that sounds human",
    description: "ElevenLabs generates ultra-realistic voices from text in 29 languages. Clone any voice, create audiobooks or podcast voiceovers. Free tier includes 10,000 characters per month.",
    category: "Audio",
    tags: ["voice", "text-to-speech", "audio", "podcast"],
    url: "https://elevenlabs.io",
    rating: 4.9,
    reviews: 7800,
    badge: "Editor's Pick",
    free_tier: "Free (10K chars/mo)"
  },
  {
    id: "suno",
    name: "Suno AI",
    tagline: "Generate full songs with vocals from a text prompt",
    description: "Suno creates complete radio-quality songs from just a text description. Pick genre, mood, and theme — it handles lyrics, melody, and vocals. Free plan gives 50 credits per day.",
    category: "Audio",
    tags: ["music", "songs", "generation"],
    url: "https://suno.com",
    rating: 4.7,
    reviews: 5600,
    badge: "Trending",
    free_tier: "Free (50 credits/day)"
  },
  {
    id: "grammarly",
    name: "Grammarly",
    tagline: "AI writing assistant that catches every mistake",
    description: "Grammarly checks grammar, spelling, clarity, and tone in real time across Gmail, Docs, LinkedIn, and every site you type on. Free tier covers the essentials perfectly.",
    category: "Writing",
    tags: ["grammar", "writing", "proofreading"],
    url: "https://grammarly.com",
    rating: 4.7,
    reviews: 22100,
    badge: "Most Popular",
    free_tier: "Free forever (basic)"
  },
  {
    id: "quillbot",
    name: "QuillBot",
    tagline: "Paraphrase, summarize, and rewrite with AI",
    description: "QuillBot is the go-to AI writing tool for paraphrasing, summarizing, grammar checking, and citation generation. Very popular among students. Free tier allows 125 words per paraphrase.",
    category: "Writing",
    tags: ["paraphrase", "summarize", "students"],
    url: "https://quillbot.com",
    rating: 4.6,
    reviews: 14500,
    badge: "Free",
    free_tier: "Free (125 words limit)"
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    tagline: "AI search engine that cites its sources",
    description: "Perplexity combines AI with real-time web search. Ask any question and get a cited, accurate answer with sources. Great for research and fact-checking. Free tier is extremely generous.",
    category: "Research",
    tags: ["search", "research", "citations"],
    url: "https://perplexity.ai",
    rating: 4.8,
    reviews: 9300,
    badge: "Editor's Pick",
    free_tier: "Free forever"
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    tagline: "Google's AI reads your docs and answers questions",
    description: "NotebookLM lets you upload PDFs and docs, then ask AI questions about them. Generates summaries, study guides, and audio podcast overviews of your documents. 100% free.",
    category: "Research",
    tags: ["documents", "study", "research", "summarize"],
    url: "https://notebooklm.google.com",
    rating: 4.8,
    reviews: 6100,
    badge: "Trending",
    free_tier: "100% Free"
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot Free",
    tagline: "AI code completion inside VS Code — now free",
    description: "GitHub Copilot's free tier gives 2,000 code completions and 50 chat messages per month inside VS Code and other editors. Supports all languages. Perfect for CS students and devs.",
    category: "Coding",
    tags: ["coding", "vscode", "autocomplete"],
    url: "https://github.com/features/copilot",
    rating: 4.9,
    reviews: 11200,
    badge: "Most Popular",
    free_tier: "Free (2K completions/mo)"
  },
  {
    id: "codeium",
    name: "Codeium",
    tagline: "Unlimited free AI code completion for developers",
    description: "Codeium offers unlimited free AI code completion, chat, and search across 70+ languages and 40+ editors. No credit card, no limits on the free plan. Best free Copilot alternative.",
    category: "Coding",
    tags: ["coding", "autocomplete", "free unlimited"],
    url: "https://codeium.com",
    rating: 4.7,
    reviews: 5400,
    badge: "Free Unlimited",
    free_tier: "Unlimited free"
  },
  {
    id: "otter",
    name: "Otter.ai",
    tagline: "AI meeting transcription and notes — free forever plan",
    description: "Otter.ai transcribes meetings, lectures, and conversations in real time. Free plan includes 300 minutes per month — perfect for students recording lectures or freelancers on client calls.",
    category: "Productivity",
    tags: ["transcription", "meetings", "notes"],
    url: "https://otter.ai",
    rating: 4.5,
    reviews: 4900,
    badge: "Free",
    free_tier: "Free (300 mins/mo)"
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    tagline: "AI built right into your notes and workspace",
    description: "Notion AI helps you write, summarize, translate, and brainstorm directly inside your Notion pages. If you already use Notion for notes or project management, this is a no-brainer add-on.",
    category: "Productivity",
    tags: ["notes", "productivity", "writing", "workspace"],
    url: "https://notion.so/product/ai",
    rating: 4.6,
    reviews: 8800,
    badge: "Trending",
    free_tier: "Free trial (20 responses)"
  },
  {
    id: "gamma",
    name: "Gamma",
    tagline: "AI presentation maker — no PowerPoint needed",
    description: "Gamma generates beautiful presentations, documents, and webpages from a single prompt in seconds. Free plan gives you 400 AI credits and unlimited viewer links. Way faster than PowerPoint.",
    category: "Productivity",
    tags: ["presentations", "slides", "documents"],
    url: "https://gamma.app",
    rating: 4.7,
    reviews: 6300,
    badge: "Editor's Pick",
    free_tier: "Free (400 credits)"
  }
];

const CATEGORIES = ["All", "Chatbot", "Design", "Image Generation", "Video", "Audio", "Writing", "Research", "Coding", "Productivity"];